site_name: SimCES
site_url: http://foo
site_description: Documentation of Simulation Environment of Complex Energy System (SimCES)
copyright: Copyright &copy; 2021 Tampere University and VTT Technical Research Centre of Finland
docs_dir: markdown
site_dir: docs
extra_css:
    - css/extra.css
theme:
    name: mkdocs
    custom_dir: overrides/
nav:
    - Manual for User:
        - Installation: core_user_install.md
        - Running a simulation: core_user_run-sim.md
        - Getting logged data: core_user_logger.md
        - Platform-managed and externally managed components: core_user_platf-ext-mgm.md
        - Time and synchronization: core_user_time-sync.md
    - Manual for Developer:
        - Communication with topics, queues and exchanges: core_dev_topics-etc.md
        - Conventions of messaging: core_dev_conventions-msg.md
        - Conventions of naming: core_dev_conventions-naming.md
        - Creating new component: core_dev_create_cmp.md
        - Exchanges:
            - Management exchange: core_dev_exchange_mgmt.md
            - Simulation-specific exchanges: core_dev_exchange_sim.md
        - Message structures:
            - Overview: core_dev_msg.md
    - Domain-specific parts:
        - Index: domain_index.md
        - Domain-specific conventions: domain_conventions.md
