site_name: SimCES
site_description: Documentation of Simulation Environment of Complex Energy System (SimCES)
copyright: Copyright &copy; 2021 Tampere University and VTT Technical Research Centre of Finland
docs_dir: markdown
site_dir: docs
extra_css:
    - css/extra.css
theme:
    name: mkdocs
    custom_dir: overrides/
nav:
    - Getting started: getting_started.md
    - Core:
        - Index: core_index.md
        - Manual for User:
            - Features: core_user_features.md
        - Manual for Developer: core_dev.md
    - Domain:
        - Index: domain_index.md
        - Domain-specific conventions: domain_conventions.md
    - Conventions in specification: spec_conventions
