site_name: SimCES
# TODO: Update website URL once public!
site_url: http://foo
site_description: Documentation of Simulation Environment of Complex Energy System (SimCES)
copyright: Copyright &copy; 2021 Tampere University and VTT Technical Research Centre of Finland
docs_dir: markdown
site_dir: docs
extra_css:
    - css/extra.css
theme:
    name: mkdocs
    custom_dir: overrides/
    
# See README.txt for the naming convention of files!
nav:
    - Use:
        - Features: core_features.md
        - Installation: core_install.md
        - Run simulation:
            - Run simulation: core_run.md
            - Follow running simulation: core_follow-run.md
        - Log API: core_log-api.md
    - Develop:
        - Basic concepts:
            - Time and synchronization with epochs: core_time.md
            - Platform-managed and externally managed components: core_cmp-mgmt.md
            - Service-oriented architecture: core_soa.md
        - How to develop:
            - Creating new component: core_create-cmp.md
            - Conventions of messaging: core_conv-msg.md
            - Conventions of naming: core_conv-name.md
            - Pseudocode reference: core_pseudocode.md
            - Simulation Tools package:
                - Simulation Tools package: core_sim-tools.md
                - AbstractSimulationComponent: core_abstractsimulationcomponent.md
            - Workflow of component in simulation: core_workflow-sim.md
            - Workflow of start and end: core_workflow-start-end.md
        - Communication:
            - Topics, queues and exchanges: core_topics-queues-exchanges.md
            - Exchange, management: core_exchange-mgmt.md
            - Exchange, simulation-specific: core_exchange-sim.md
            - Topics (core): core_topics.md
            - Reliable messaging in RabbitMQ: core_rabbitmq-reliability.md
            - Footprint of AMQP items: core_amqp-footprint.md
        - Message structures (core):
            - Message structures (core): core_msg.md
            - Message type names (core): core_msgtype.md
            - Units of measure (UCUM): core_ucum.md
            - Message - AbstractMessage: core_msg-abstractmessage.md
            - Message - AbstractResult: core_msg-abstractresult.md
            - Message - Epoch: core_msg-epoch.md
            - Message - SimState: core_msg-simstate.md
            - Message - Start: core_msg-start.md
            - Message - Status: core_msg-status.md
            - Block - Quantity: core_block-quantity.md
            - Block - Quantity array: core_block-quantity-array.md
            - Block - Time series: core_block-time-series.md
        - Platforms internals:
            - Logging system: core_logging-system.md
            - LogWriter: core_logwriter.md
            - PlatformManager: core_platformmanager.md
            - Simulation lifecycle: core_lifecycle.md
            - SimulationManager: core_simulationmanager.md
    - Energy domain:
        - Energy-domain-specific conventions: energy_conventions.md
        - Components (energy):
            - Grid (DSS): energy_grid-dss.md
        - Message structures (energy):
            - ControlState.PowerSetpoint: energy_controlstate-powersetpoint.md
            - DMSNetworkState.Current: energy_dmsnetworkstate-current.md
        - Message type names (energy): energy_msgtype.md
        - Software packages: energy_software-pkg.md
        - Topics (energy):
            - Topics (energy): energy_topics.md
    - About...: about.md
