site_name: SimCES
site_url: http://foo
site_description: Documentation of Simulation Environment of Complex Energy System (SimCES)
copyright: Copyright &copy; 2021 Tampere University and VTT Technical Research Centre of Finland
docs_dir: markdown
site_dir: docs
extra_css:
    - css/extra.css
theme:
    name: mkdocs
    custom_dir: overrides/
nav:
    - Manual for User:
        - Installation: core_install.md
        - Running a simulation: core_run.md
        - Getting logged data: core_logger.md
        - Platform-managed and externally managed components: core_cmp-mgmt.md
        - Time and synchronization: core_time.md
    - Manual for Developer:
        - Communication with topics, queues and exchanges: core_communication.md
        - Conventions of messaging: core_conv-msg.md
        - Conventions of naming: core_conv-name.md
        - Creating new component: core_create-cmp.md
        - Exchanges:
            - Management exchange: core_exchange-mgmt.md
            - Simulation-specific exchanges: core_exchange-sim.md
        - Message structures:
            - Overview: core_msg.md
    - Domain-specific parts:
        - Index: domain_index.md
        - Domain-specific conventions: domain_conventions.md
