site_name: SimCES
# TODO: Update website URL once public!
site_url: http://foo
site_description: Documentation of Simulation Environment of Complex Energy System (SimCES)
copyright: Copyright &copy; 2021 Tampere University and VTT Technical Research Centre of Finland
docs_dir: markdown
site_dir: docs
extra_css:
    - css/extra.css
theme:
    name: mkdocs
    custom_dir: overrides/
    
# See README.txt for the naming convention of files!
nav:
    - User manual:
        - Installation: core_install.md
        - Running a simulation:
            - Following a running simulation: core_follow-run.md
        - Getting logged data: core_logger.md
        - Platform-managed and externally managed components: core_cmp-mgmt.md
        - Time and synchronization: core_time.md
    - Developer manual:
        - Conventions of messaging: core_conv-msg.md
        - Conventions of naming: core_conv-name.md
        - Communication:
            - Topics, queues and exchanges: core_topics-queues-exchanges.md
            - Exchange, management: core_exchange-mgmt.md
            - Exchange, simulation-specific: core_exchange-sim.md
            - Topics (core): core_topics.md
            - Reliable messaging in RabbitMQ: core_rabbitmq-reliability.md
            - Footprint of AMQP items: core_amqp-footprint.md
        - Message structures (core):
            - Message structures (core): core_msg.md
            - Message type names (core): core_msgtype.md
            - Units of measure (UCUM): core_ucum.md
        - How to develop:
            - Creating new component: core_create-cmp.md
            - Pseudocode reference: core_pseudocode.md
            - Service-oriented architecture: core_soa.md
            - Simulation Tools package:
                - Simulation Tools package: core_sim-tools.md
                - AbstractSimulationComponent: core_abstractsimulationcomponent
            - Workflow of component in simulation: core_workflow-sim.md
            - Workflow of start and end: core_workflow-start-end.md
    - Domain-specific parts:
        - Domain-specific conventions: domain_conventions.md
        - Message structures (domain):
            - ControlState.PowerSetpoint: domain_controlstate-powersetpoint.md
            - DMSNetworkState.Current: domain_dmsnetworkstate-current.md
        - Message type names (domain): domain_msgtype.md
    - About...: about.md
