site_name: SimCES
# TODO: Update website URL once public!
site_url: http://foo
site_description: Documentation of Simulation Environment of Complex Energy System (SimCES)
copyright: Copyright &copy; 2021 Tampere University and VTT Technical Research Centre of Finland
docs_dir: markdown
site_dir: docs
extra_css:
    - css/extra.css
theme:
    name: mkdocs
    custom_dir: overrides/
    
# See README.txt for the naming convention of files!
nav:
    - Manual for User:
        - Installation: core_install.md
        - Running a simulation: core_run.md
        - Getting logged data: core_logger.md
        - Platform-managed and externally managed components: core_cmp-mgmt.md
        - Time and synchronization: core_time.md
    - Manual for Developer:
        - Communication with topics, queues and exchanges: core_communication.md
        - Conventions of messaging: core_conv-msg.md
        - Conventions of naming: core_conv-name.md
        - Creating new component: core_create-cmp.md
        - Exchanges:
            - Management exchange: core_exchange-mgmt.md
            - Simulation-specific exchanges: core_exchange-sim.md
        - Message structures (core):
            - Message structures (core): core_msg.md
            - Units of measure (UCUM): core_ucum.md
        - Message type names (core): core_msgtype.md
    - Domain-specific parts:
        - Domain-specific conventions: domain_conventions.md
        - Message structures (domain):
            - ControlState.PowerSetpoint: domain_controlstate-powersetpoint.md
            - DMSNetworkState.Current: domain_dmsnetworkstate-current.md
        - Message type names (domain): domain_msgtype.md
